import Head from "next/head";

const forgot2 = () => {
  return (
    <div>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <a href="#" className="BackButton">
            Back
          </a>
          <div className="ForgotText">Check your email</div>
          <div className="ForgotText1">
            We have sent password reset link to <br />
            <strong>bingwen@hotmail.com</strong>
          </div>
          <div className="forgot2">
            Didn’t receive the email?
            <span style={{ color: "#1996FC" }}> Click to resend</span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default forgot2;
