/* eslint-disable react-hooks/rules-of-hooks */
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";

const passFormat =
  /^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^A-Za-z0-9])(.{8,24})$/;

const forgot3 = () => {
  const [password, setPassword] = useState("");
  const [resetPass, setResetPass] = useState("");
  const [validPass, setValidPass] = useState(false);
  const [samePass, setSamePass] = useState(false);

  const [passwordShown, setPasswordShown] = useState(false);
  const router = useRouter();

  const handleSubmit = (e: any) => {
    e.preventDefault();
    if (validPass) {
      if (samePass) {
        router.push("/forgot4");
      }
    }
  };

  const togglePassword = () => {
    setPasswordShown(passwordShown ? false : true);
  };

  let flag = false;
  useEffect(() => {
    if (passFormat.test(password)) {
      setValidPass(true);
      // eslint-disable-next-line react-hooks/exhaustive-deps
      flag = true;
    }
  }, [password]);

  useEffect(() => {
    if (flag) {
      if (password !== resetPass) {
        console.log("false set");
        setSamePass(false);
      }
      if (password === resetPass) {
        setSamePass(true);
      }
    }
  }, [resetPass]);

  return (
    <div>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css"
        />
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="main">
        <div>
          <Link href="/loginpage">
            <span className="BackButton">Back</span>
          </Link>
          <div className="ForgotText">Set new password</div>
          <div className="ForgotText1">
            Your new password must be different from <br />
            previous used passwords.
          </div>
          <div className="greyEmail">Password</div>
          <input
            className="input3"
            type={passwordShown ? "text" : "password"}
            name="password"
            onChange={(e) => {
              setPassword(e.target.value);
            }}
          />
          <i
            className={`fa ${
              passwordShown ? "fa-eye-slash" : "fa-eye"
            } password-icon1`}
            onClick={togglePassword}
          />
          <div className="emailRectangle"></div>
          {validPass ? (
            <div className="line-h1" style={{ color: "green" }}>
              Your Password is Valid
            </div>
          ) : (
            <div className="line-h1" style={{ width: "400px" }}>
              Minimum 8 characters with at least 1 number and a symbol
            </div>
          )}
          <div className="greyPass">Password</div>
          <input
            className="input4"
            type={passwordShown ? "text" : "password"}
            name="confirmPass"
            onChange={(e) => {
              setResetPass(e.target.value);
            }}
          />
          <i
            className={`fa ${
              passwordShown ? "fa-eye-slash" : "fa-eye"
            } password-icon2`}
            onClick={togglePassword}
          />
          <div className="passRectangle"></div>

          <div
            className="line-h2"
            style={!samePass ? { color: "#212121" } : { color: "green" }}
          >
            Both password must match.
          </div>

          <button className="InstructionButton2" onClick={handleSubmit}>
            <p className="inner-btn">Reset Password</p>
          </button>
          <a href="#" className="cancelButton2">
            Cancel
          </a>
        </div>
      </main>
    </div>
  );
};

export default forgot3;
